name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-myProject-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.os }}
    
    steps:
      - run: vi /etc/pki/tls/certs/ca-bundle.crt
